/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:c4dc4717-e05a-4583-8d36-a66d0ae6a47d",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_29GjJbAcP",
    "aws_user_pools_web_client_id": "53iluj9t1rbu97ea26klo3v1f8",
    "oauth": {}
};


export default awsmobile;
